'''
config.py :: Jackie Schellberg :: Last updated 6/12/2024 

This configures both the modulation (simpleTX_sim) and the demodulation (simpleRX_sim) code. 
'''

''' General Params '''
FS = 200e3 
# FS = 2.4e6         # (Hz) USRP Sampling Rate (FS/2 corresponding to the capture bandwidth) 
BW = 2500           # Chirp Bandwidth, (Hz) 
# BW = 20000 
SF = 7              # Spreading factor/rate 
CR = 0              # Hamming coding rate: 0 is no coding, up to 4

''' Specifics for generating experiment files '''
NUMPKTS = 50      # Total number of packets in an experiment file. 
PAYLOAD_LEN = 100 # Number of symbols per CSS packet 

''' Experiment Related ''' 
# exp_root_folder = '../../experiment_data_JUNE2'                    # Toplevel file containing multiple experiments 
# exp_folder = 'SF_7N_128BW_2500FS_200000NPKTS_50PLEN_100CR_0'       # Specific trial folder containing raw data and experiment details. subfolder of exp_root_folder 
# exp_root_folder = '../../HAM_TESTS'                                # Toplevel file containing multiple experiments 
exp_root_folder = '../../TEST_CONFIG'  
# exp_root_folder = '../../ARA_EXPERIMENT_TX_DATA'
# exp_root_folder = '../../HAM_ONES_TEST'         

''' Demodulation Only. This will not impact experiment file generation '''
RAW_FS = 500e3   # Number of samples rx_stream waits from ZMQ until sending to demodulation 
# RAW_FS = 2.4e6   
# exp_folder = '0HzS_SF_6N_64BW_2500FS_200000NPKTS_50PLEN_100CR_0'    # Specific trial folder containing raw data and experiment details. subfolder of exp_root_folder.
# exp_folder = '0HzS_SF_7N_128BW_2500FS_200000NPKTS_50PLEN_100CR_0'                                                                     #      This name is generated by genExperimentFile.py
# exp_folder = '0HzS_SF_7N_128BW_2500FS_200000NPKTS_50PLEN_100CR_0'  
exp_folder = '0HzS_SF_7N_128BW_2500FS_200000NPKTS_50PLEN_100CR_0'  
# exp_folder = '0HzS_SF_7N_128BW_2500FS_200000NPKTS_5PLEN_10CR_0'  
# exp_folder = '0HzS_SF_5N_32BW_2500FS_200000NPKTS_50PLEN_100CR_0'

fine_sync_method = 0 # 0 uses doppler slope detection, 1 uses correlator, 2 uses self-chirping 

intra_pkt_doppler_correction = True # turn on/off doppler correction between sucessive symbols

